//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kilidsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int ADID { get; set; }
        public Nullable<int> hID { get; set; }
        public int agID { get; set; }
    
        public virtual Agancy Agancy { get; set; }
        public virtual Home Home { get; set; }
    }
}
