//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kilidsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Home()
        {
            this.Advertises = new HashSet<Advertise>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string City { get; set; }
        public string Neighborhood { get; set; }
        public int Size { get; set; }
        public long Price { get; set; }
        public Nullable<long> RentPrice { get; set; }
        public int Age { get; set; }
        public int Adtype { get; set; }
        public int Usage { get; set; }
        public int Roomnum { get; set; }
        public int Parkinglot { get; set; }
        public int Balcony { get; set; }
        public int Elevator { get; set; }
        public int Store { get; set; }
        public byte[] Image { get; set; }
        public string Explain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertise> Advertises { get; set; }
    }
}
